### PR TITLE
Retry snap installs

### LINKED ISSUE #2: Zypper error codes mishandled
[packaging/manager/utils.go](https://github.com/juju/packaging/blob/ba21344fff207f4fa06b0a08bac386b179a2e6a1/manager/utils.go#L91-96) contains some logic that tests the exit status of a running command. It's hard coded to allow `100` to retry: 

```go
// Both apt-get and yum return 100 on abnormal execution due to outside
// issues (ex: momentary dns failure).
code = waitStatus.ExitStatus()
if code != 100 {
	break
}
```

Similar logic is used in [config/global_constants.go](https://github.com/juju/packaging/blob/ba21344fff207f4fa06b0a08bac386b179a2e6a1/config/global_constants.go#L20):
```bash
function package_manager_loop {
    local rc=
    while true; do
        if ($*); then
                return 0
        else
                rc=$?
        fi
        if [ $rc -eq 100 ]; then
                sleep 10s
                continue
        fi
        return $rc
    done
```

OpenSUSE uses [different codes](https://en.opensuse.org/SDB:Zypper_manual#EXIT_CODES) and `100` should also fail. Here is the full list for reference. It's unclear whether any of them indicate potentially transient errors related to the network.

```plain
       0 - ZYPPER_EXIT_OK
           Successful run of zypper with no special info.

       1 - ZYPPER_EXIT_ERR_BUG
           Unexpected situation occurred, probably caused by a bug.

       2 - ZYPPER_EXIT_ERR_SYNTAX
           zypper was invoked with an invalid command or option, or a bad syntax.

       3 - ZYPPER_EXIT_ERR_INVALID_ARGS
           Some of provided arguments were invalid. E.g. an invalid URI was provided to the addrepo command.

       4 - ZYPPER_EXIT_ERR_ZYPP
           A problem is reported by ZYPP library.

       5 - ZYPPER_EXIT_ERR_PRIVILEGES
           User invoking zypper has insufficient privileges for specified operation.

       6 - ZYPPER_EXIT_NO_REPOS
           No repositories are defined.

       7 - ZYPPER_EXIT_ZYPP_LOCKED
           The ZYPP library is locked, e.g. packagekit is running.

       8 - ZYPPER_EXIT_ERR_COMMIT
           An error occurred during installation or removal of packages. You may run zypper verify to repair any
           dependency problems.

       100 - ZYPPER_EXIT_INF_UPDATE_NEEDED
           Returned by the patch-check command if there are patches available for installation.

       101 - ZYPPER_EXIT_INF_SEC_UPDATE_NEEDED
           Returned by the patch-check command if there are security patches available for installation.

       102 - ZYPPER_EXIT_INF_REBOOT_NEEDED
           Returned after a successful installation of a patch which requires reboot of computer.

       103 - ZYPPER_EXIT_INF_RESTART_NEEDED
           Returned after a successful installation of a patch which requires restart of the package manager itself.
           This means that one of patches to be installed affects the package manager itself and the command used
           (e.g.  zypper update) needs to be executed once again to install any remaining patches.

       104 - ZYPPER_EXIT_INF_CAP_NOT_FOUND
           Returned by the install and the remove command in case any of the arguments does not match any of the
           available (or installed) package names or other capabilities.

       105 - ZYPPER_EXIT_ON_SIGNAL
           Returned upon exiting after receiving a SIGINT or SIGTERM.

       106 - ZYPPER_EXIT_INF_REPOS_SKIPPED
           Some repository had to be disabled temporarily because it failed to refresh. You should check your
           repository configuration (e.g.  zypper ref -f).
```

### PR DESCRIPTION
**Pull request by SimonRichardson**
The way this worked previously was that it would exit out early if it
wasn't a DNS exit code (100). So for snap installs, this would mean a
retry wouldn't happen as that was a 1.

The code is changed so that we have a set of high-order functions that
allow you to express what we want to achieve from calling the packaging
manager install.

Unfortunately we had to make some breaking changes and bump to v2.

----

The running of a retry command now attempts to split the work into 2
places. The running of the command and if the error is a fatal error.
With this in place we don't need to check for retrying locally and we
can ask each individual package manager if they can retry.

The runner previously had way to much knowledge and pushed apt, yum,
snap and zypper to all behave the same. This isn't the case and not how
each package manager works. See #2 

This simple change, isn't so simple because the tests patch the hell out
of things and calls commands locally on each system, which is confusing.

The changes here try and straighten it all out, but could do with
re-write of the tests as they're observed testing, rather than expected
conditional testing.

Fixes #2 as a driveby.

### CODE REVIEW

File: manager/snap.go [hunk 1]
```diff
@@ -77,7 +77,21 @@ func (snap *Snap) ChangeChannel(pack, channel string) error {
...
+	installError := func(err error, exitCode int, cmdOutput string) (bool, error) {
+		switch exitCode {
+		case 0:
+			return false, nil
+		case 1:
+			return true, nil
+		}
+
+		// If the error is a DNS retryable error then ensure we capture that.
+		if retryable, retryableErr := DNSRetryableError(err, exitCode, cmdOutput); retryableErr != nil || !retryable {
```
Comment (achilleasa) [inline manager/snap.go:89]: Why not just push that logic to the interface used by `cmder`?

Comment (SimonRichardson) [reply manager/snap.go:89]: You don't actually want to retry every command, so in order to make this more generic to all commands, you need to pass through the type of command running. This is where it gets a little messy, you essentially need to pass a string of the command context running everywhere and that's unwieldy to me.

Unless you have different retryers depending on the command?

Comment (achilleasa) [reply manager/snap.go:89]: I meant the `DNSRetryableError` bit since that's backend-specific.

File: manager/interface.go [hunk 2]
```diff
@@ -9,12 +9,15 @@ package manager
...
-
-	"github.com/juju/packaging/commands"
 )
 
 // PackageManager is the interface which carries out various
 // package-management related work.
+//
+// TODO (stickupid): Both the PackageManager and PackageCommander from the
+// commands package should be merged. The layout of the packaging package is
+// over engineered. The commands should be placed directly into the package
```
Comment (achilleasa) [inline manager/interface.go:19]: s/over engineered/over-engineered/ ?

**Review by achilleasa — APPROVED** [review]

**Comment by SimonRichardson** [comment]
$$merge$$
